"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2gu6i7#l33j--%fs=38yo$4gaq^8lo-5fd(j*g#u2(9gzx&whe"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bet_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# 👇 to add in settings
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media_cdn")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





















# MPESA Configuration variables

MPESA_CONSUMER_KEY    = 'eHgUVx1FKTuMW6nBHNASuOimnehlKGbt'
MPESA_CONSUMER_SECRET = 'FgQAZCAVU8IWcmCC'

#Shortcode to use for transactions. For sandbox  use the Shortcode 1 provided on test credentials page
MPESA_SHORT_CODE  = '174379' # 382777
MPESA_B2C_PARTY_A = '600977' # 382777

MPESA_SHORTCODE_TYPE = 'CustomerPayBillOnline'

MPESA_TOKEN_URL            = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
MPESA_DEPOSITE_URL         = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
MPESA_DEPOSITE_RESULT_URL  = "https://mezizbet.com/api/user/deposit/result/"
MPESA_WITHDRAW_URL         = "https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest"
MPESA_WITHDRAW_RESULT_URL  = "https://mezizbet.com/api/user/withdraw/result/"
MPESA_WITHDRAW_TIMEOUT_URL = "https://mezizbet.com/api/user/withdraw/timeout/"
                
MPESA_PASSKEY              = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SECURITY_CREDENTIAL  = "Nht8YWLyBNhSIUPx0yR6eSjgAwhBLnl3ULU+Lowu/ibzqsfVZCZZ1+7YDPSpTsdMlIUegrm1nRhS0B5ZyoLW525ZPWs4E8DLtLtjvMgYy5MnFEdr2VJk8z90akHI59rIIkB2EewwymJ8w4MPQvfpPWx4hgPbM4MDjDY7gW66Se9qh/5Ih8DjqnR+mrpmN/lvQ3NHhYoItYfgeMduaubnz1RVz3e2GOQxLUxinTTih9Nt/J2BgRRy6OWIzpqMtRVQC12M3TWZ1mXYB1chZtU0uYF6bYthdDIGerGA4xt7D7JDW0ZrVpUOWT7+tnLZrWxOKYwdWhmBcS37FPu9qIvRQQ=="

# Username for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)
MPESA_INITIATOR_USERNAME = 'testapi'

# Plaintext password for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)
MPESA_INITIATOR_SECURITY_CREDENTIAL = 'Safaricom999!*!' 




